/**
 * Scrumboard API
 * API for accessing Scrumboard project data.
 *
 * OpenAPI spec version: v1
 * Contact: jboinembaome@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ActivityFieldDto } from './activityFieldDto';
import { AdherentDto } from './adherentDto';

export interface ActivityDto { 
    id?: number;
    createdDate?: Date;
    activityType?: 'Added' | 'Updated' | 'Removed' | 'Finished'| 'NotFinished' | 'Checked' | 'Unchecked';
    activityField?: ActivityFieldDto;
    oldValue?: string;
    newValue?: string;
    adherent?: AdherentDto;
}