/**
 * Scrumboard API
 * API for accessing Scrumboard project data.
 *
 * OpenAPI spec version: v1
 * Contact: jboinembaome@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type AttachmentType = 0 | 1;

export const AttachmentType = {
    NUMBER_0: 0 as AttachmentType,
    NUMBER_1: 1 as AttachmentType
};