/**
 * Scrumboard API
 * API for accessing Scrumboard project data.
 *
 * OpenAPI spec version: v1
 * Contact: jboinembaome@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AdherentDto } from './adherentDto';
import { BoardSettingDto } from './boardSettingDto';
import { LabelDto } from './labelDto';
import { ListBoardDetailDto } from './listBoardDetailDto';
import { TeamDto } from './teamDto';

export interface BoardDetailDto { 
    id?: number;
    name?: string;
    uri?: string;
    adherent?: AdherentDto;
    team?: TeamDto;
    boardSetting?: BoardSettingDto;
    listBoards?: Array<ListBoardDetailDto>;
    labels?: Array<LabelDto>;
}