/**
 * Scrumboard API
 * API for accessing Scrumboard project data.
 *
 * OpenAPI spec version: v1
 * Contact: jboinembaome@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AdherentDto } from './adherentDto';

export interface CommentDto { 
    id?: number;
    message?: string;
    createdDate?: Date;
    modifiedDate?: Date;
    adherent?: AdherentDto;
}