/**
 * Scrumboard API
 * API for accessing Scrumboard project data.
 *
 * OpenAPI spec version: v1
 * Contact: jboinembaome@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ActivityFieldDto } from './activityFieldDto';
import { UserDto } from './userDto';

export interface ActivityDto { 
    id?: number;
    createdDate?: Date;
    activityType?: string;
    activityField?: ActivityFieldDto;
    oldValue?: string;
    newValue?: string;
    user?: UserDto;
}