/**
 * Scrumboard API
 * API for accessing Scrumboard project data.
 *
 * OpenAPI spec version: v1
 * Contact: jboinembaome@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AdherentDto } from './adherentDto';
import { AttachmentDto } from './attachmentDto';
import { ChecklistDto } from './checklistDto';
import { LabelDto } from './labelDto';

export interface UpdateCardCommand { 
    id?: number;
    name?: string;
    description?: string;
    suscribed?: boolean;
    dueDate?: Date;
    labels?: Array<LabelDto>;
    adherents?: Array<AdherentDto>;
    attachments?: Array<AttachmentDto>;
    checklists?: Array<ChecklistDto>;
}