/**
 * Scrumboard API
 * API for accessing Scrumboard project data.
 *
 * OpenAPI spec version: v1
 * Contact: jboinembaome@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BoardSettingDto } from './boardSettingDto';

export interface BoardDto { 
    id?: number;
    name?: string;
    initials?: string;
    uri?: string;
    isPinned?: boolean;
    lastActivity?: Date;
    members?: number;
    boardSetting?: BoardSettingDto;
}