export * from './activities.service';
import { ActivitiesService } from './activities.service';
export * from './adherents.service';
import { AdherentsService } from './adherents.service';
export * from './boards.service';
import { BoardsService } from './boards.service';
export * from './cards.service';
import { CardsService } from './cards.service';
export * from './comments.service';
import { CommentsService } from './comments.service';
export * from './labels.service';
import { LabelsService } from './labels.service';
export * from './scrumboardWeb.service';
import { ScrumboardWebService } from './scrumboardWeb.service';
export * from './teams.service';
import { TeamsService } from './teams.service';
export * from './weatherForecast.service';
import { WeatherForecastService } from './weatherForecast.service';
export const APIS = [ActivitiesService, AdherentsService, BoardsService, CardsService, CommentsService, LabelsService, ScrumboardWebService, TeamsService, WeatherForecastService];
