/**
 * Scrumboard API
 * API for accessing Scrumboard project data.
 *
 * OpenAPI spec version: v1
 * Contact: jboinembaome@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { CommentCreationModel } from '../model/commentCreationModel';
import { CreateCommentCommandResponse } from '../model/createCommentCommandResponse';
import { ProblemDetails } from '../model/problemDetails';
import { UpdateCommentCommand } from '../model/updateCommentCommand';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class CommentsService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Get card comments.
     * 
     * @param cardId Id of the card.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiCardsCardIdCommentsGet(cardId: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public apiCardsCardIdCommentsGet(cardId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public apiCardsCardIdCommentsGet(cardId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public apiCardsCardIdCommentsGet(cardId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (cardId === null || cardId === undefined) {
            throw new Error('Required parameter cardId was null or undefined when calling apiCardsCardIdCommentsGet.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('get',`${this.basePath}/api/cards/${encodeURIComponent(String(cardId))}/comments`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete a comment on a card.
     * 
     * @param cardId Id of the card.
     * @param id Id of the comment.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiCardsCardIdCommentsIdDelete(cardId: number, id: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public apiCardsCardIdCommentsIdDelete(cardId: number, id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public apiCardsCardIdCommentsIdDelete(cardId: number, id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public apiCardsCardIdCommentsIdDelete(cardId: number, id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (cardId === null || cardId === undefined) {
            throw new Error('Required parameter cardId was null or undefined when calling apiCardsCardIdCommentsIdDelete.');
        }

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiCardsCardIdCommentsIdDelete.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/api/cards/${encodeURIComponent(String(cardId))}/comments/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update a comment on a card.
     * 
     * @param cardId Id of the card.
     * @param id Id of the comment.
     * @param body Comment to be updated.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiCardsCardIdCommentsIdPut(cardId: number, id: number, body?: UpdateCommentCommand, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public apiCardsCardIdCommentsIdPut(cardId: number, id: number, body?: UpdateCommentCommand, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public apiCardsCardIdCommentsIdPut(cardId: number, id: number, body?: UpdateCommentCommand, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public apiCardsCardIdCommentsIdPut(cardId: number, id: number, body?: UpdateCommentCommand, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (cardId === null || cardId === undefined) {
            throw new Error('Required parameter cardId was null or undefined when calling apiCardsCardIdCommentsIdPut.');
        }

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling apiCardsCardIdCommentsIdPut.');
        }


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<any>('put',`${this.basePath}/api/cards/${encodeURIComponent(String(cardId))}/comments/${encodeURIComponent(String(id))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create a comment on a card.
     * 
     * @param cardId Id of the card.
     * @param body Comment to be added.
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiCardsCardIdCommentsPost(cardId: number, body?: CommentCreationModel, observe?: 'body', reportProgress?: boolean): Observable<CreateCommentCommandResponse>;
    public apiCardsCardIdCommentsPost(cardId: number, body?: CommentCreationModel, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CreateCommentCommandResponse>>;
    public apiCardsCardIdCommentsPost(cardId: number, body?: CommentCreationModel, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CreateCommentCommandResponse>>;
    public apiCardsCardIdCommentsPost(cardId: number, body?: CommentCreationModel, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (cardId === null || cardId === undefined) {
            throw new Error('Required parameter cardId was null or undefined when calling apiCardsCardIdCommentsPost.');
        }


        let headers = this.defaultHeaders;

        // authentication (Bearer) required
        if (this.configuration.apiKeys && this.configuration.apiKeys["Authorization"]) {
            headers = headers.set('Authorization', this.configuration.apiKeys["Authorization"]);
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json',
            'text/json',
            'application/_*+json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<CreateCommentCommandResponse>('post',`${this.basePath}/api/cards/${encodeURIComponent(String(cardId))}/comments`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
